# Generated by Django 2.2.4 on 2019-08-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20190803_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
