# Generated by Django 2.2.3 on 2019-07-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ryans',
            fields=[
                ('product_title', models.CharField(max_length=1000)),
                ('product_link', models.URLField(max_length=1000)),
                ('img_link', models.URLField(max_length=1000)),
                ('price', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Startech',
            fields=[
                ('product_title', models.CharField(max_length=1000)),
                ('product_link', models.URLField(max_length=1000)),
                ('img_link', models.URLField(max_length=1000)),
                ('price', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ryans', models.ForeignKey(db_column='ryans', on_delete=django.db.models.deletion.CASCADE, to='webs.Ryans')),
                ('startech', models.ForeignKey(db_column='startech', on_delete=django.db.models.deletion.CASCADE, to='webs.Startech')),
            ],
        ),
    ]
