# Generated by Django 2.2.3 on 2019-07-29 12:27

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ryans',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('description', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=500))),
                ('display_size', models.CharField(max_length=10)),
                ('display_type', models.CharField(max_length=30)),
                ('graphics_memory', models.CharField(max_length=30)),
                ('img_link', models.URLField(max_length=10000)),
                ('model', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=20)),
                ('product_link', models.URLField(max_length=10000)),
                ('product_title', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=10)),
                ('ram_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1000)),
                ('storage', djongo.models.fields.DictField()),
                ('website', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Startech',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('display_size', models.CharField(max_length=10)),
                ('graphics_memory', models.CharField(max_length=30)),
                ('img_link', models.URLField(max_length=10000)),
                ('price', models.CharField(max_length=20)),
                ('product_link', models.URLField(max_length=10000)),
                ('product_title', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=10)),
                ('ram_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1000)),
                ('storage', djongo.models.fields.DictField()),
                ('website', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ryans', models.ForeignKey(db_column='ryans', on_delete=django.db.models.deletion.CASCADE, to='webs.Ryans')),
                ('startech', models.ForeignKey(db_column='startech', on_delete=django.db.models.deletion.CASCADE, to='webs.Startech')),
            ],
        ),
    ]
