# Generated by Django 2.2.3 on 2019-07-31 06:55

from django.db import migrations, models
import djongo.models.fields
import webs.models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0002_auto_20190731_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('description', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=500))),
                ('display_size', models.CharField(max_length=10)),
                ('display_type', models.CharField(max_length=30)),
                ('graphics_memory', models.CharField(max_length=30)),
                ('img_link', models.URLField(max_length=10000)),
                ('model', models.CharField(max_length=500)),
                ('product_title', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=10)),
                ('ram_type', models.CharField(max_length=100)),
                ('storage', djongo.models.fields.DictField()),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('websites', djongo.models.fields.ListField(verbose_name=djongo.models.fields.EmbeddedModelField(model_container=webs.models.Website, null=True))),
            ],
        ),
    ]
