# Generated by Django 2.2.4 on 2019-08-02 13:26

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ryans',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('description', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=1000))),
                ('display_size', models.CharField(max_length=10)),
                ('display_type', models.CharField(max_length=30)),
                ('graphics_memory', models.CharField(max_length=30)),
                ('img_link', models.URLField(max_length=10000)),
                ('model', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('product_link', models.URLField(max_length=10000)),
                ('product_title', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=10)),
                ('ram_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('storage', djongo.models.fields.DictField()),
                ('website', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
