# Generated by Django 2.2.4 on 2019-08-07 06:37

from django.db import migrations, models
import djongo.models.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('description', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=500))),
                ('display_size', models.CharField(max_length=10)),
                ('graphics_memory', models.CharField(max_length=30)),
                ('img_link', models.URLField(max_length=10000)),
                ('product_title', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=10)),
                ('ram_type', models.CharField(max_length=100)),
                ('storage', djongo.models.fields.DictField()),
                ('_id', models.CharField(max_length=100)),
                ('websites', djongo.models.fields.ListField(verbose_name=djongo.models.fields.EmbeddedModelField(model_container=products.models.Website, null=True))),
            ],
        ),
        migrations.CreateModel(
            name='Ryans',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('description', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=1000))),
                ('display_size', models.CharField(max_length=10)),
                ('display_type', models.CharField(max_length=30)),
                ('graphics_memory', models.CharField(max_length=30)),
                ('img_link', models.URLField(max_length=10000)),
                ('model', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('product_link', models.URLField(max_length=10000)),
                ('product_title', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=10)),
                ('ram_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('storage', djongo.models.fields.DictField()),
                ('website', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Startech',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('description', djongo.models.fields.ListField(verbose_name=models.CharField(max_length=1000))),
                ('display_size', models.CharField(max_length=10)),
                ('graphics_memory', models.CharField(max_length=30)),
                ('img_link', models.URLField(max_length=10000)),
                ('price', models.IntegerField(default=0)),
                ('product_link', models.URLField(max_length=10000)),
                ('product_title', models.CharField(max_length=1000)),
                ('ram', models.CharField(max_length=10)),
                ('ram_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('storage', djongo.models.fields.DictField()),
                ('website', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product_link', models.URLField(max_length=10000)),
                ('status', models.CharField(max_length=1000)),
                ('img_link', models.URLField(max_length=10000)),
            ],
        ),
    ]
