# Generated by Django 2.2.4 on 2019-08-20 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_notification_updated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
